config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root  'tweets#index'
    get   'tweets'      =>  'tweets#index'
    get   'tweets/new'  =>  'tweets#new'
    post  'tweets'      =>  'tweets#create'
    delete 'tweets/:id' => 'tweets#destroy'

    get   'tweets/:id/edit' => 'tweets#edit'
     patch  'tweets/:id' => 'tweets#update'
  end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

 before_action :move_to_index, except: :index

  def index
    @tweets = Tweet.order("created_at DESC").page(params[:page]).per(10)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(text: tweet_params[:text], user_id: current_user.id)
  end

  def destroy
      tweet = Tweet.find(params[:id])
      tweet.destroy if tweet.user_id == current_user.id
    end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
      tweet = Tweet.find(params[:id])
      tweet.update(tweet_params) if tweet.user_id == current_user.id
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <style type="text/css" href="./style.css"></style>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<nav class="#26a69a teal lighten-1">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">blog</a>

      <ul id="nav-mobile" class="right hide-on-med-and-down">

        <% if user_signed_in? %>

        <li><a href="badges.html">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </a></li>

        <li><a href="sass.html">
          <a class="post" href="/tweets/new">投稿する</a>
        </a></li>

        <% else %>

        <li><a href="sass.html">
          <%= link_to "ログイン", new_user_session_path, class: 'post' %>
        </a></li>

        <li><a href="badges.html">
          <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
        </a></li>

        <% end %>

      </ul>



    </div>
  </nav>

<%= yield %>

<script type="text/javascript" src="./app.js"></script>

<footer>
      <p>
        Copyright miniblog 2018.
      </p>
    </footer>

</body>
</html>

app/views/tweets/create.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/tweets">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/edit.html.erb
<div class="contents row">
    <%= form_for @tweet, url: "/tweets/#{@tweet.id}" do|f| %>
      <h3>
        編集する
      </h3>
      <%= f.text_field :text  %>
    <%= f.submit "EDIT" %>
    <% end %>
  </div>

app/views/tweets/index.html.erb
<div class="contents row" >



  <% @tweets.each do |tweet| %>
<div class="row">
      <div class="col s12 m5">
        <div class="card-panel teal">
          <span class="black-text"><%= tweet.text %><br>
          </span>
          <% if user_signed_in? && current_user.id == tweet.user.id %>

          <div class="more">
          <ul class="more_list">

            <li>
              <%= button_to '編集', "/tweets/#{tweet.id}/edit", method: :get, :style=>"color:#26a69a;" %>
            </li>

            <li>
              <%= button_to '削除', "/tweets/#{tweet.id}", method: :delete, :style=>"color:#26a69a;" %>
            </li>
          </ul>
        </div>

  <% end %>
        </div>
      </div>

    </div>
  <% end %>
<%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <%= form_for @tweet, url: tweets_path do |f| %>
    <h3>
      投稿する
    </h3>
      <%= f.text_field :text  %>
    <%= f.submit "SENT" %>
  <% end %>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
</div>